# Generated by Django 5.0.3 on 2024-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_pagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('data', models.CharField(max_length=255, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запрос на связь',
                'verbose_name_plural': 'Запросы на связь',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='pagecontact',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Соощении'},
        ),
        migrations.RenameField(
            model_name='pagecontact',
            old_name='numbers',
            new_name='number',
        ),
        migrations.AddField(
            model_name='pagecontact',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagecontact',
            name='message',
            field=models.TextField(default=1, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagecontact',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
