# Generated by Django 5.0.3 on 2024-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram url')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube url')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp url')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
