# Generated by Django 5.0.3 on 2024-04-04 07:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_services_slide_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Фотография услуги'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='video/', verbose_name='Фотография для баннера'),
        ),
    ]
